[build]
  base = "client/"
  publish = "build/"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--legacy-peer-deps --production=false"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
